### ISSUE TITLE
the css

### ISSUE THREAD

**Issue by agneshraok** [agneshraok/the-odin-project#4]
```css
*{
    border: 1px solid red;
}

div#stats-block{
    display: flex;
    justify-content: center;
    padding : 30px;
}

#stats-block > .stats{
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    width : 300px;
    height : 500px;
}

.vector{
    width:200px;
    height:200px;
    margin: 20px;
}

.score{
    margin: 20px;
    width: 50px;
    height: 20px;
}

#choices {
    display: flex;
    justify-content: center;
    padding : 50px;
}

.btn {
    padding: 30px;
    border-radius: 5px;
    margin: 5px;
}


```
